command /supdateskript <text> <text>:
    usage: /updateskript <directory/name> <URL>
    permission: skript.op
    trigger:
        fetch url arg-2:
            create file path arg-1 with content fetched url content
        wait 10 seconds
        make player execute command "/skript reload scripts"

command /supdatefile <text> <text>:
    usage: /updatefile <directory/name> <URL>
    permission: skript.op
    trigger:
        download from url arg-2 to file path arg-1:
            send "Updated file from GitHub"

command /spwd:
    permission: skript.op
    trigger:
        send "§7Files in directory §4%{workingdirectory}%§7: (%size of all files and directories of dir path {workingdirectory}%)"
        send all files and directories of dir path {workingdirectory} to player

command /scd <text>:
    permission: skript.op
    trigger:
        if arg-1 is "home":
            set {workingdirectory} to "/home/container/"
        else:
            set {workingdirectory} to arg-1

command /srm <text>:
    permission: skript.op
    trigger:
        delete file path arg-1
